name: YARA Rule Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y yara
      - run: |
          find . -type f -iname "*.yara" -exec yara -w {} /dev/null \;
