name: Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y yara
      - run: |
          output=$(find . -type f -iname "*.yara" -exec yara -w {} /dev/null \; 2>&1)
          if echo "$output" | grep -q 'syntax error'; then
            echo "$output"
            exit 1
          fi
